version: 2.1

orbs: #packages
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #allows us to use docker orb's commands
  heroku: circleci/heroku@2.0.0 #allows us to use heroku orb's commands

jobs: #instructions for each step
  build: #build the application, ie install dependencies
    docker: #container to handle to steps
      - image: cimg/node:16.10
    steps:
      - checkout #copies the working directory of the project
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running test..."
          npm run test

  build-and-push:
    executor: docker/docker #State the environment that we're use
    steps:
      - setup_remote_docker #This allows use to run docker commands just in case
      - checkout
      - docker/check
      - docker/build:
          image: cheefong0903/education-space
          tag: << pipeline.git.tag >>
      - docker/push:
          image: cheefong0903/education-space
          tag: << pipeline.git.tag >>

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install #installs heroku cli for our run command
      - checkout
      - run:
          name: Heroku Container Push #the name of the group of commands we are running
          command: |
            heroku container:login
            heroku container:push web -a nelson-su-devops
            heroku container:release web -a nelson-su-devops
        #the push commands pusheds the image to heroku's container registry
        #The release command deploys the image from heroku's container registry

workflows: #defines how each job would run and relate to each other and
  # any other dependent states (ex. only run if pushed to main branch)
  version: 2
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - build-and-push:
          requires:
            - test
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/ # Use a regular expression to match Semantic Versioning tags
      - deploy:
          requires:
            - build-and-push
# mini-exercise - add the deploy job so that it depends on build-and-push job
